<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE students [
  <!ELEMENT students (student+)>
  <!ELEMENT student (id, name, course)>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT course (#PCDATA)>
]>
<students>
	<student>
		<id>1</id>
		<name>A</name>
		<course>SYBCA</course>
	</student>
</students>